name: Jekyll with GitHub Pages dependencies preinstalled
on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy configs from ghp
        run: | 
          echo "* Current hash: $(git rev-parse HEAD)"
          if [[ "$(basename $(pwd))" != "ghp" ]]; then
            git config user.name 'github'
            git config user.email 'noreply@github.com'
            echo '* Building $(basename $(pwd)) with ghp.yml'
            if [[ -n $(git status --short) ]]; then echo "*** Updated ghp"; fi
            wget https://github.com/${{ github.actor }}/ghp/tarball/main -O - | tar -xz --one-top-level=ghp --strip-components=1;
            ghpArr=( "Gemfile" "_config.yml" "favicon.ico" "_includes" "_layouts" "assets")
            for item in ${ghpArr[@]}; do cp -ruf ghp/$item . && echo "* copied $item"; done
            rm -rf ghp && echo "* rm -rf ghp \n"
          fi
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
